[package]
name = "ekans-rust"
version = "0.1.0"
authors = ["Ajinkya Prabhu <ajinkyaprabhu97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
